[package]
name = "graph_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
petgraph = "0.6"
tempfile = "3.2.0"
tempdir = "0.3"
ndarray = "0.15.3"
ndarray-stats = "0.4.0"
plotters = "0.3"

